En esta guia se vera como se pueden usar los metodos de los modelos de tu baes de datos sequelize


Para poder usar los metodos que traen los modelos simplemente hay que importarlos una vez esten y configurados

import Tasks from ./turuta


Esto ya te permite usar cada metodo que trae consigo el objeto Model de sequilize que creaste lo que te va
permitirte usar todos los metodos siguientes dentro de los controladores

[[create()]]
[[bulkCreate()]]
[[findOrCreate()]]
[[findAll()]]
[[findByPk()]]
[[findOne()]]
[[update()]]
[[destroy()]]
[[add()]]
[[get()]]
[[remove()]]

Para saber como usarlos simplemente buscar en la documentacion


